name: PR test
on: [pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        # reporter: github-pr-review
        reporter: github-pr-check
        flags: --linelength=50
