name: PR test
on: [pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        # reporter: github-pr-review
        reporter: github-pr-check
        flags: --linelength=50
