name: PR test
on: [pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        # reporter: github-pr-review
        reporter: github-pr-check
        flags: --linelength=50
