name: Self test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 2
    - name: testbuild
      run: |
        cd testdata
        g++ --version
        g++ ./test.cpp -o test
        ls
        ./test
