name: Self test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 2
    - name: testbuild
      run: |
        cd testdata
        g++ --version
        g++ ./test.cpp -o test
        ls
        ./test
